### ISSUE TITLE
Authentication mechanism

### ISSUE THREAD

**Issue by hjoshi123** [CSCI-5828-Foundations-Sftware-Engr/TeamBlume#1]
User should be able to enter his/her credentials (Google account) and should be greeted with a welcome message after the flow.

Acceptance Criteria:

* Validation of social media login.
* User must be able to relogin once he/she signs up.
* Welcome page shouldn't be visible without login.

**Comment by sriharsharedd-y** [comment]
Authentication mechanism successfully created with supabase.
