### ISSUE TITLE
Trends Page

### ISSUE THREAD

**Issue by rakshitha31** [CSCI-5828-Foundations-Sftware-Engr/TeamBlume#12]
Trends Page with two views

1. Most Searched Products
2. price trend over the week for the searched product

**Comment by ajaymopidevi** [comment]
Trends page is modified to show:
1. Category wise most search products
2. Price trends over the week in the product page

**Comment by ajaymopidevi** [comment]
Sub tasks: #6 , #31, #54, #55

**Comment by ajaymopidevi** [comment]
Trends page is split into 2 main tasks:
1. Most Searched Products in each category (Displayed at the bottom of products)
2. Price Trends on a platform for a product
