### ISSUE TITLE
Price trend chart Page

### ISSUE THREAD

**Issue by rakshitha31** [CSCI-5828-Foundations-Sftware-Engr/TeamBlume#9]
There are two views

1. - https://github.com/CSCI-5828-Foundations-Sftware-Engr/TeamBlume/issues/8 
2. - https://github.com/CSCI-5828-Foundations-Sftware-Engr/TeamBlume/issues/13

**Comment by ajaymopidevi** [comment]
Added trends of most searched products in each category page and price trends over a week for each product
